app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authenticate/', include('authentication_app.urls')),
    path('memories/', include('memories.urls')),
    path('', RedirectView.as_view(url='memories/')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication_app/urls.py
from django.urls import path
from . import views


app_name = "authenticate"

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout')
]

memories/urls.py
from django.urls import path
from . import views

app_name = "memories"

urlpatterns = [
    path('', views.Index.as_view(), name='main'),
    path('<str:username>/', views.MemoryListView.as_view(), name="list"),
    path('<str:username>/create/', views.MemoryCreateView.as_view(), name="create"),
    path('<str:username>/create-embed/', views.MemoryEmbedView.as_view(), name="embed"),
    path('<str:username>/<int:pk>/', views.MemoryDetailView.as_view(), name='detail'),
    path('<str:username>/<int:pk>/edit/', views.MemoryEditView.as_view(), name='edit'),
    path('<str:username>/<int:pk>/delete/', views.MemoryDeleteView.as_view(), name='delete'),

]

memories/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

import datetime


def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.author.id, filename)


class Memory(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    media = models.FileField(upload_to=user_directory_path,
                             null=True,
                             blank=True)
    embed_id = models.CharField(max_length=50, default="", blank=True)
    created = models.DateTimeField()
    mime_type = models.CharField(max_length=30, default="")

    def save(self, *args, **kwargs):
        if self.created is None:
            self.created = datetime.datetime.now()
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('memories:detail',
                       kwargs={
                            'pk': self.pk,
                            'username': self.author.username})
    
    def __str__(self):
        return self.title

memories/forms.py
from django import forms
from django.core.exceptions import ValidationError

from urllib.parse import urlparse, parse_qs

from . import utils, constants, models


class MemoryForm(forms.ModelForm):
    media = forms.FileField(required=False)

    class Meta:
        model = models.Memory
        fields = ('title', 'content', 'media')

    def clean_media(self):
        media = self.cleaned_data.get('media', None)
        if media is not None:
            mime = utils.check_in_memory_mime(media)
            if not utils.is_good_mimes(mime):
                raise ValidationError(f"Such file type '{mime}'\
                                        is restricted for this app"
                                      )
        return media


class EmbedForm(forms.Form):
    embed_id = forms.CharField()

    def clean(self):
        cleaned_data = super().clean()
        embed_id = cleaned_data.get('embed_id')
        embed_data_dict = utils.get_data_from_embed(embed_id)
        if embed_data_dict is None:
            raise ValidationError("Can't get data from that youtube video id.")
        cleaned_data.update({'embed_data': embed_data_dict})
        return cleaned_data

    def clean_embed_id(self):
        cleaned_embed_url = self.cleaned_data.get('embed_id')
        parsed_url = urlparse(cleaned_embed_url)
        if parsed_url.netloc != constants.YOUTUBE_DOMAIN\
           or parsed_url.path != constants.YOUTUBE_PATH:
            raise ValidationError('Domain must be {}{}'.format(
                constants.YOUTUBE_DOMAIN,
                constants.YOUTUBE_PATH)
                )
        query_set = parse_qs(parsed_url.query)
        embed_id = query_set.get('v')
        if embed_id is None:
            raise ValidationError('No post id')
        return embed_id[0]

    def save(self, user):
        embed_data = self.cleaned_data.get('embed_data')
        data_to_update = {
            'author': user,
        }
        embed_data.update(data_to_update)
        memory = models.Memory.objects.create(**embed_data)
        return memory

memories/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView
from django.http import Http404

from . import models, forms, utils


class Index(View):
    model = User
    template_name = 'memories/index.html'

    def get(self, request):
        users = self.model.objects.all()
        return render(request, self.template_name, {'users': users})


class MemoryListView(View):
    model = models.Memory
    template_name = 'memories/memory_list.html'

    def get(self, request, username=None):
        get_object_or_404(User, username=username)
        memories = self.model.objects.filter(author__username=username)
        return render(request,
                      self.template_name,
                      {'memories': memories, 'page_username': username})


class MemoryCreateView(View):
    form_class = forms.MemoryForm
    template_name = "memories/memory_create.html"

    def get(self, request, username, *args, **kwargs):
        if request.user.username != username:
            raise Http404
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, username):
        if request.user.username != username:
            raise Http404
        file = request.FILES
        form = self.form_class(request.POST, file)
        if form.is_valid():
            memory = form.save(commit=False)
            memory.author = request.user
            media = file.get('media', None)
            if media is not None:
                mime = utils.check_in_memory_mime(media)
                memory.mime_type = mime
            memory.save()
            return redirect(reverse(
                'memories:detail',
                kwargs={'username': request.user.username, 'pk': memory.pk})
                )
        return render(request, self.template_name, {'form': form})


class MemoryEmbedView(View):
    form_class = forms.EmbedForm
    template_name = "memories/embed_form.html"

    def get(self, request, username):
        if request.user.username != username:
            raise Http404
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, username):
        if request.user.username != username:
            raise Http404
        form = self.form_class(request.POST)
        if form.is_valid():
            memory = form.save(request.user)
            return redirect(reverse(
                'memories:detail',
                kwargs={"username": username, 'pk': memory.id})
                )
        return render(request, self.template_name, {'form': form})


class MemoryDetailView(DetailView):
    model = models.Memory
    context_object_name = 'memory'


class MemoryEditView(View):
    model = models.Memory
    form_class = forms.MemoryForm
    template_name = "memories/memory_edit.html"

    def get(self, request, username, pk, *args, **kwargs):
        if request.user.username != username:
            raise Http404
        memory = get_object_or_404(self.model, pk=pk)
        form = self.form_class(instance=memory)
        return render(request, self.template_name,
                      {'form': form, 'memory': memory}
                      )

    def post(self, request, username, pk):
        if request.user.username != username:
            raise Http404

        memory = get_object_or_404(self.model, pk=pk)
        form = self.form_class(request.POST, instance=memory)
        if form.is_valid():
            form.save()
            return redirect(reverse(
                'memories:detail',
                kwargs={'username': request.user.username, 'pk': memory.pk})
                )
        return render(request,
                      self.template_name,
                      {'form': form, 'memory': memory}
                      )


class MemoryDeleteView(View):
    model = models.Memory
    template_name = 'memories/memory_confirm_delete.html'

    def get(self, request, username, pk):
        if request.user.username != username:
            raise Http404
        memory = get_object_or_404(self.model, pk=pk)
        return render(request, self.template_name, {'memory': memory})

    def post(self, request, username, pk):
        if request.user.username != username:
            raise Http404
        memory = get_object_or_404(self.model, pk=pk)
        memory.delete()
        return redirect(reverse(
            'memories:list',
            kwargs={'username': username})
            )

memories/templates/memories/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    
    <title>{% block title %}Memories{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/main.css' %}" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <script src="{% static 'js/main.js' %}"></script>
  </head>
  <body>
    {% block header %}
    <header>
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'memories:main' %}">Main</a>
            </li>
            {% block navigation %}{% endblock %}
          </ul>
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'memories:list' username=user.username %}">Your Memories</a>
                <a class="nav-link" href="{% url 'authenticate:logout' %}">Logout</a>
            {% else %}
                <a class="nav-link" href="{% url 'authenticate:login' %}">Login</a>
                <a class="nav-link" href="{% url 'authenticate:register' %}">Register</a>
            {% endif %}
        </nav>
      </div>
    </header>
    {% endblock %}


    <div class="container">
      <div class="row justify-content-center">
        <div class="col col-md-6">{% block content %} {% endblock %}</div>
      </div>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

memories/templates/memories/embed_form.html
{% extends "memories/base.html" %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
    <input type="text" name="type" id="mimeType" hidden>
</form>

{% endblock %}

memories/templates/memories/index.html
{% extends 'memories/base.html' %}


{% block content %}
    <p>Check Users memories</p>
    {% for user in users %}
        <p><a href="{% url 'memories:list' username=user.username %}">{{user.username}}</a></p>
    {% empty %}
        <p>Поспешите успеть стать первым пользователем!</p>
    {% endfor %}
{% endblock %}

memories/templates/memories/memory_confirm_delete.html
{% extends "memories/base.html" %}
{% block title %}
    Delete Sumbit
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ memory.title }}"?</p>
    <input class="btn btn-danger" type="submit" value="Delete">
    <a href="{% url 'memories:edit' username=user.username pk=memory.pk %}" class="btn btn-primary">Go to edit</a>     
    <a href="{% url 'memories:detail' username=user.username pk=memory.pk %}" class="btn btn-primary">Go to detail</a>     
</form>
{% endblock %}

memories/templates/memories/memory_create.html
{% extends "memories/base.html" %}
{% load static crispy_forms_tags %}

{% block title %}
    Create
{% endblock %}

{% block content %}
<h3>Create new memory</h3>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        {{ form.title|as_crispy_field }}
        {{ form.content|as_crispy_field }}
        {{ form.media|as_crispy_field }}
    <input type="submit" class="btn btn-primary" value="Save">
</form>

<p>Or you can just add Youtube link</p>
<a href="{% url 'memories:embed' username=request.user.username %}">Add YouTube Link</a>
{% endblock %}

memories/templates/memories/memory_detail.html
{% extends "memories/base.html" %}
{% load startswith %}

{% block title %}
    Detail
{% endblock %}

{% block content %}
<h1>{{ memory.title }}</h1>
<p>{{ memory.content }}</p>
            {% if memory.mime_type|startswith:'video' %}
                <video width="320" height="240" controls>
                <source src="{{ memory.media.url }}" type="video/mp4">
                Your browser does not support the video tag.
                </video> 
            {% elif memory.mime_type|startswith:'image' %}
                <img style='width: 100%' src="{{memory.media.url}}" alt="image">
            
            {% elif memory.mime_type|startswith:'embed' %}
                 <iframe
                    src="https://www.youtube.com/embed/{{ memory.embed_id }}">
                </iframe> 

            {% endif %}
<p>Published: {{ memory.created|date }}</p>
{% if request.user == memory.author %}
<a href="{% url 'memories:edit' username=user.username pk=memory.pk %}" class="btn btn-primary">Edit</a>
{% endif %}

{% endblock %}

memories/templates/memories/memory_edit.html
{% extends "memories/base.html" %}


{% block title %}
  Edit
{% endblock %}

{%block navigation%}
<li class="nav-item">
  <a class="nav-link" href="{% url 'memories:detail' username=request.user.username pk=memory.pk %}">Detail</a>
</li>
{% endblock %}


{% block content %}
{% load startswith crispy_forms_tags %}
  <form method="post">
    {% csrf_token %}
    {{ form.title|as_crispy_field }}
    {{ form.content|as_crispy_field }}
    <div class="form-group">
    <input type="text" hidden value="" />
    {% if memory.mime_type|startswith:'video' %}
      <video style="width: 100%; height: 270px;" controls>
        <source src="{{ memory.media.url }}" type="video/mp4" />
        Your browser does not support the video tag.
      </video>
      {% elif memory.mime_type|startswith:'image' %}
      <img style="width: 100%" src="{{memory.media.url}}" alt="image" />

      {% elif memory.mime_type|startswith:'embed' %}
      <iframe style="width: 100%; height: 270px;" src="https://www.youtube.com/embed/{{ memory.embed_id }}">
      </iframe>
      {% endif %}
    </div>
    <input type="submit" class="btn btn-success" value="Update"/>
    <a href="{% url 'memories:delete' username=request.user.username pk=memory.pk %}" class="btn btn-danger">Delete</a>
  </form>
{% endblock %}

memories/templates/memories/memory_list.html
{% extends "memories/base.html" %}

{% block title %}
    {% if user.username == page_username %}
        Yours Memories    
    {% else %}
        {{ page_username }}`s memories
    {% endif %}
{% endblock %}

{% load startswith %}

{% block content %}
<h1>Memmories</h1>
{% if user.username == page_username %}
    <a href="{% url 'memories:create' username=user.username%}" class="btn btn-primary">Add new memory</a>
{% endif %}
{% for memory in memories %}
<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ memory.title }}</h5>
        <p class="card-text">{{ memory.content }}</p>
        <p class="card-text">{{ memory.created|date}}</p>
        <div>
            {% if memory.mime_type|startswith:'video' %}
                <video style="width: 100%; height: 270px;" controls>
                    <source src="{{ memory.media.url }}" type="{{ memory.mime_type }}">
                    <source src="{{ memory.media.url }}" type="video/mp4">
                    Your browser does not support the video tag.
                </video> 
            {% elif memory.mime_type|startswith:'image' %}
                <img style='width: 100%; height: 270px;' src="{{memory.media.url}}" alt="image">
            
            {% elif memory.mime_type|startswith:'embed' %}
                 <iframe style="width: 100%; height: 270px;"
                    src="https://www.youtube.com/embed/{{ memory.embed_id }}">
                </iframe> 

            {% endif %}
        </div>
        <a href="{% url 'memories:detail' username=page_username pk=memory.pk %}" class="btn btn-primary">Detail</a>
    </div>
</div>
{% empty %}
    <p>No memories yet.<p>
{% endfor %}
{% endblock %}